version: "2.0"

services:
    web:
        container_name: ${COMPOSE_PROJECT_NAME}-web
        image: nginx
        ports:
            - "${DOCKER_PORT_HTTP}:80"
            - "${DOCKER_PORT_HTTPS}:443"
        depends_on:
            - engine
        volumes:
            - ../server:/var/www/html
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - jetdocker-ssl-certificate:/certs
        environment:
            - VIRTUAL_HOST
    engine:
        container_name: ${COMPOSE_PROJECT_NAME}-engine
        image: jetpulp/php72-fpm
        volumes:
            - ../server:/var/www/html
            - ./engine/php.ini:/usr/local/etc/php/conf.d/php.ini

        depends_on:
            - db
            - blackfire
        working_dir: "/var/www/html"
        environment:
            - USER_UID
            - USER_GROUP
            - SERVER_NAME
            - SERVER_NAME_ALIAS
            - XDEBUG_ENABLED
        networks:
            - default
            - mailhog_default
    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mariadb:10.0
        ports:
            - "${DOCKER_PORT_MYSQL}:3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE
    blackfire:
      container_name: ${COMPOSE_PROJECT_NAME}-blackfire
      image: blackfire/blackfire
      environment:
          - BLACKFIRE_SERVER_ID
          - BLACKFIRE_SERVER_TOKEN
    search-replace-db:
        container_name: ${COMPOSE_PROJECT_NAME}-search-replace-db
        image: jetpulp/search-replace-db
        volumes:
            - ./db/config.yml:/app/config.yml
        depends_on:
            - db
        environment:
            - DB_ENV_MYSQL_USER=root
            - DB_ENV_MYSQL_PASSWORD=root
            - DB_ENV_MYSQL_DATABASE=$MYSQL_DATABASE
            - SERVER_NAME
            - SERVER_NAME_ALIAS

volumes:
  dbdata:
    external:
      name: ${COMPOSE_PROJECT_NAME}-dbdata
  jetdocker-ssl-certificate:
    external: true

networks:
    default:
        driver: bridge
    mailhog_default:
        external:
            name: mailhog_default